
export const CONSTANTS:any = {}

CONSTANTS.DATA_DIR = '/data'
CONSTANTS.RAW_DIR = CONSTANTS.DATA_DIR+'/raw'
CONSTANTS.DATASET_DIR = CONSTANTS.DATA_DIR+'/dataset'
CONSTANTS.JSON_DIR = CONSTANTS.DATA_DIR+'/dataset/json'
CONSTANTS.IMG_DIR = CONSTANTS.DATA_DIR+'/dataset/img'
CONSTANTS.SAMPLES = CONSTANTS.DATA_DIR+'/dataset/samples.json'


